# permissions for end users to view hdfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hdfs-viewer-role
rules:
- apiGroups:
  - qy.dataworkbench.com
  resources:
  - hdfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qy.dataworkbench.com
  resources:
  - hdfs/status
  verbs:
  - get
