apiVersion: qy.dataworkbench.com/v1
kind: HDFS
metadata:
  name: hdfs
spec:
  version: 3.x  # 2.x or 3.x
  image: dataworkbench/hdfs-metrics:3.1.0
  namenode:
    name: namenode
    storageClass: namenode-disks
    capacity: 10Gi
    replicas: 2
  journalnode:
    name: journalnode
    storageClass: journalnode-disks
    capacity: 10Gi
    replicas: 3
  datanode:
    name: datanode
    storageClass: journalnode-disks
    capacity: 10Gi
    datadirs:
      - dn1    #  多目录的子目录，
      - dn2
    replicas: 3
  zkQuorum: "zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181"
  clusterConfig:
    - property: "dfs.namenode.handler.count"
      value: "10"
    - property: "dfs.datanode.handler.count"
      value: "10"
    - property: "dfs.replication"
      value: "2"