apiVersion: qy.dataworkbench.com/v1
kind: HDFS
metadata:
  name: test
spec:
  version: 3.1.0  # hadoop version
  image: dataworkbench/hdfs-metrics:3.1.0
  namenode:
    name: namenode
    storageClass: nn-disks
    capacity: 10Gi
    replicas: 2
  journalnode:
    name: journalnode
    storageClass: jn-disks
    capacity: 10Gi
    replicas: 3
  datanode:
    name: datanode
    storageClass: dn-disks
    capacity: 10Gi
    datadirs:
      - dn1    #  多目录的子目录，
      - dn2
    replicas: 3
  zkQuorum: "zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181"
  hdfsSite:
    - property: "dfs.namenode.handler.count"
      value: "10"
    - property: "dfs.replication"
      value: "2"
  yarn:
    name: yarn
    rmReplicas: 1
    nmReplicas: 3